### ISSUE TITLE
"Error executing action `install` on resource 'package[autoconf]'"

### ISSUE THREAD

**Issue by dmatt** [vccw-team/vccw#112]
I'm trying to setup using these instructions: http://vccw.cc/.

Vagrant and VirtualBox are up to date.

I've tried registering my SSH key per this issue here:  #76

Log: https://gist.github.com/dmatt/36cc670cf17945f0a9b9bd9894ddd2e9

cc: @miya0001

**Comment by miya0001** [comment]
I am sorry to be late. 😓 

Did you solve this problem?
Please download `.zip` from [here](https://github.com/vccw-team/vccw/archive/2.21.0.zip), then `vagrant up`.

Some git client sometimes changes line-endings, so chef cookbooks will be broken.
Your problem looks it.

**Comment by dmatt** [comment]
I'm going to try this soon, thank you for the suggestion!

**Comment by fredericpfisterer** [comment]
I have the same issue and downloading the zip did not solve it :-( Any ideas why ?

**Comment by miya0001** [comment]
@fredericpfisterer 

Are there any virtual machines in your host?
Please try `vagrant global-status`.

If you have another machine, please destroy them.

**Comment by fredericpfisterer** [comment]
I destroyed all of them and I still can't go through vccw installation process : 

`==> vccw.dev: [2016-06-12T07:19:30+00:00] INFO: Forking chef instance to converge...
==> vccw.dev: [2016-06-12T07:19:30+00:00] WARN: 
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> vccw.dev: encrypted, but chef is not able to detect forged replies or man in the middle
==> vccw.dev: attacks.
==> vccw.dev: 
==> vccw.dev: To fix this issue add an entry like this to your configuration file:
==> vccw.dev: 
==> vccw.dev: ```
==> vccw.dev:   # Verify all HTTPS connections (recommended)
==> vccw.dev:   ssl_verify_mode :verify_peer
==> vccw.dev: 
==> vccw.dev:   # OR, Verify only connections to chef-server
==> vccw.dev:   verify_api_cert true
==> vccw.dev: ```
==> vccw.dev: 
==> vccw.dev: To check your SSL configuration, or troubleshoot errors, you can use the
==> vccw.dev: `knife ssl check` command like so:
==> vccw.dev: 
==> vccw.dev: ```
==> vccw.dev:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> vccw.dev: ```
==> vccw.dev: 
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: Starting Chef Client, version 11.16.4
==> vccw.dev: [2016-06-12T07:19:30+00:00] INFO: *** Chef 11.16.4 ***
==> vccw.dev: [2016-06-12T07:19:30+00:00] INFO: Chef-client pid: 29352
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Setting the run_list to ["recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Run List is [recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Run List expands to [wpcli, wpcli::install, vccw]
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Starting Chef Run for vagrant-64edfb90
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Running start handlers
==> vccw.dev: [2016-06-12T07:19:42+00:00] INFO: Start handlers complete.
==> vccw.dev: Compiling Cookbooks...
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Cloning resource attributes for package[perl] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Previous package[perl]: /tmp/vagrant-chef/668890655c0faf424c8868b86b65632a/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Current  package[perl]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/default.rb:51:in `from_file'
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Cloning resource attributes for service[apache2] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Previous service[apache2]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/default.rb:24:in `from_file'
==> vccw.dev: [2016-06-12T07:19:42+00:00] WARN: Current  service[apache2]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/default.rb:221:in `from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Cloning resource attributes for file[/etc/httpd/conf.d/ssl.conf] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Previous file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/default.rb:84:in `block in from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Current  file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/mod_ssl.rb:31:in `from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Cloning resource attributes for template[/etc/httpd/ports.conf] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Previous template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/default.rb:195:in `from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Current  template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/apache2/recipes/mod_ssl.rb:37:in `from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Cloning resource attributes for directory[/var/lib/mysql] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Previous directory[/var/lib/mysql]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Current  directory[/var/lib/mysql]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] INFO: Could not find previously defined grants.sql resource
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Cloning resource attributes for service[mysql] from prior resource (CHEF-3694)
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Previous service[mysql]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/server.rb:154:in `from_file'
==> vccw.dev: [2016-06-12T07:19:43+00:00] WARN: Current  service[mysql]: /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/server.rb:218:in `from_file'
==> vccw.dev: Recipe: build-essential::rhel
==> vccw.dev:   
==> vccw.dev: * package[autoconf] action install
==> vccw.dev:     
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: ================================================================================
==> vccw.dev:     
==> vccw.dev: Error executing action `install` on resource 'package[autoconf]'
==> vccw.dev:     
==> vccw.dev: ================================================================================
==> vccw.dev:     
==> vccw.dev: 
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: Mixlib::ShellOut::ShellCommandFailed
==> vccw.dev:     
==> vccw.dev: ------------------------------------
==> vccw.dev:     
==> vccw.dev: Expected process to exit with [0], but received '1'
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev: 
==> vccw.dev:     
==> vccw.dev: 14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
==> vccw.dev:     STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev:     ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev:     Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev:     
==> vccw.dev:     Cookbook Trace:
==> vccw.dev:     ---------------
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:41:in `block in from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:36:in `each'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:36:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/ruby.rb:24:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/668890655c0faf424c8868b86b65632a/cookbooks/wpcli/recipes/install.rb:10:in `from_file'
==> vccw.dev:     
==> vccw.dev:     Resource Declaration:
==> vccw.dev:     ---------------------
==> vccw.dev:     # In /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb
==> vccw.dev:     
==> vccw.dev:      38:   r = package pkg do
==> vccw.dev:      39:     action( node['build_essential']['compiletime'] ? :nothing : :install )
==> vccw.dev:      40:   end
==> vccw.dev:      41:   r.run_action(:install) if node['build_essential']['compiletime']
==> vccw.dev:     
==> vccw.dev:     Compiled Resource:
==> vccw.dev:     ------------------
==> vccw.dev:     # Declared in /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
==> vccw.dev:     
==> vccw.dev:     package("autoconf") do
==> vccw.dev:       action [:nothing]
==> vccw.dev:       retries 0
==> vccw.dev:       retry_delay 2
==> vccw.dev:       guard_interpreter :default
==> vccw.dev:       package_name "autoconf"
==> vccw.dev:       timeout 900
==> vccw.dev:       cookbook_name :"build-essential"
==> vccw.dev:       recipe_name "rhel"
==> vccw.dev:     end
==> vccw.dev:     
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: ================================================================================
==> vccw.dev:   
==> vccw.dev: Recipe Compile Error in /tmp/vagrant-chef/668890655c0faf424c8868b86b65632a/cookbooks/wpcli/recipes/install.rb
==> vccw.dev:   
==> vccw.dev: ================================================================================
==> vccw.dev:   
==> vccw.dev: 
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: Mixlib::ShellOut::ShellCommandFailed
==> vccw.dev:   
==> vccw.dev: ------------------------------------
==> vccw.dev:   
==> vccw.dev: package[autoconf] (build-essential::rhel line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: 14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev: 
==> vccw.dev:   
==> vccw.dev: ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: 
==> vccw.dev:   Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev:   
==> vccw.dev:   Cookbook Trace:
==> vccw.dev:   ---------------
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:41:in `block in from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:36:in `each'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:36:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/mysql/recipes/ruby.rb:24:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/668890655c0faf424c8868b86b65632a/cookbooks/wpcli/recipes/install.rb:10:in `from_file'
==> vccw.dev:   
==> vccw.dev:   Relevant File Content:
==> vccw.dev:   ----------------------
==> vccw.dev:   /tmp/vagrant-chef/540fd2069cf1f03777824a7ba31ae5ed/cookbooks/build-essential/recipes/rhel.rb:
==> vccw.dev:   
==> vccw.dev:    34:  end
==> vccw.dev:    35:  
==> vccw.dev:    36:  pkgs.flatten.each do |pkg|
==> vccw.dev:    37:  
==> vccw.dev:    38:    r = package pkg do
==> vccw.dev:    39:      action( node['build_essential']['compiletime'] ? :nothing : :install )
==> vccw.dev:    40:    end
==> vccw.dev:    41>>   r.run_action(:install) if node['build_essential']['compiletime']
==> vccw.dev:    42:  
==> vccw.dev:    43:  end
==> vccw.dev:    44:  
==> vccw.dev:   
==> vccw.dev:   
==> vccw.dev:   Running handlers:
==> vccw.dev: [2016-06-12T07:20:04+00:00] ERROR: Running exception handlers
==> vccw.dev:   Running handlers complete
==> vccw.dev: [2016-06-12T07:20:04+00:00] ERROR: Exception handlers complete
==> vccw.dev: [2016-06-12T07:20:04+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> vccw.dev:   Chef Client failed. 0 resources updated in 34.216274169 seconds
==> vccw.dev: [2016-06-12T07:20:04+00:00] ERROR: package[autoconf] (build-essential::rhel line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> vccw.dev: ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev: 14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
==> vccw.dev: STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev: ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev: [2016-06-12T07:20:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
`

**Comment by miya0001** [comment]
It looks problem of mirrorlist.centos.org.
Can you see http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock ?

I think it is a temporary error.

**Comment by dmatt** [comment]
>Did you solve this problem?
>Please download .zip from here, then vagrant up.

Yes! This solved the problem for me. Thanks @miya0001.
