### ISSUE TITLE
Multisite with subdomains instead of subdirectories?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [vccw-team/vccw#98]
Hello there! I was curious if there was a way for me to be allowed to use, or be given the choice of, using subdomains instead of subdirectories for a multisite setup. 

I noticed in the `install.rb` file, [lines ~231-245](https://github.com/vccw-team/vccw/blob/44bbaee60228e46bd11bb398ade55f63ddb5c541/provision/site-cookbooks/wpcli/recipes/install.rb#L231-L245), that there is a `wp core` command that sets it to `multisite-convert`.

```
# install.rb
if node[:wpcli][:is_multisite] == true then
  bash "Setup multisite" do
    user node[:wpcli][:user]
    group node[:wpcli][:group]
    cwd File.join(node[:wpcli][:wp_docroot], node[:wpcli][:wp_siteurl])
    code "WP_CLI_CONFIG_PATH=#{Shellwords.shellescape(node[:wpcli][:config_path])} wp core multisite-convert"
  end

  template File.join(node[:wpcli][:wp_docroot], node[:wpcli][:wp_home], '.htaccess') do
    source "multisite.htaccess.erb"
    owner node[:wpcli][:user]
    group node[:wpcli][:group]
    mode "0644"
  end
end
```

According to the documentation for the `wp-cli`: http://wp-cli.org/commands/core/

> [multisite-convert](http://wp-cli.org/commands/core/multisite-convert/)	Transform a single-site install into a multi-site install.
> [multisite-install](http://wp-cli.org/commands/core/multisite-install/)	Install multisite from scratch.

I'd like to be able to use the `multisite-install` command instead. As I understand it, this will allow me to have the choice (via the super admin dashboard) to choose between using subdomains or subdirectories for my multisite setup.

If there is a _different_ way for me to be able to use subdomains for my multisite setup, definitely let me know. Thank you! :smiley:

**Comment by mrgerardorodriguez** [comment]
Hello again, I did a bit more research and  looking at the `options` for [`multsite-convert`](http://wp-cli.org/commands/core/multisite-convert/), it says:

> [--subdomains]
> If passed, the network will use subdomains, instead of subdirectories. Doesn’t work with ‘localhost’.

Just to see what happens, I added the `--subdomains` flag after the `wp core multisite-convert` command on line ~236 of `install.rb`. After doing so, I am now able to use subdomains instead of subdirectories for my multisite setup! Yay! :smile: 

Would it be challenging to make this an option so I can pass the `--subdomains` flag via the `site.yml`, for example?

**Comment by mrgerardorodriguez** [comment]
Hello again, it appears there is a bit more than just adding the `--subdomains` flag to make subdomains work. One thing I hadn't considered is the fact the `hosts` file would also need to be updated once a new subdomain is added. 

Once again, I'll pose my original question, is there a way for me to use subdomains instead of subdirectories for a multisite setup using `vccw`?

Thanks for your time! :smiley:

**Comment by miya0001** [comment]
@mrgerardorodriguez 

I found following.
http://asciithoughts.com/posts/2014/02/23/setting-up-a-wildcard-dns-domain-on-mac-os-x/

Have you ever tried it?
It looks fine ... but I haven't tried yet. :smile:
